// 자동 생성된 시드 파일 — export-equipment-seed.ts 로 생성
import { EquipmentCategory, EquipmentGrade, EquipmentProcess } from '../../common/enums/equipment.enum';

export const EQUIPMENT_SEED_DATA = [
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-1",
    "name": "진공함침 및 롤프레스기(중고장비)",
    "manufacturer": "㈜테크랜드",
    "purchaseDate": "2019-03-04",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-2",
    "name": "초음파 융착기(중고장비)",
    "manufacturer": "㈜테크랜드",
    "purchaseDate": "2019-03-04",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-3",
    "name": "파우치 실링기(중고장비)",
    "manufacturer": "씨엔아이테크닉스",
    "purchaseDate": "2019-03-04",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-4",
    "name": "Pouch Forming Machine",
    "manufacturer": "mPLUS",
    "purchaseDate": "2019-03-04",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "건물-005",
    "equipmentNo": "PM-5",
    "name": "공조기 1호",
    "manufacturer": "퍼스트산업개발",
    "purchaseDate": "2019-03-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "건물-005",
    "equipmentNo": "PM-6",
    "name": "공조기 2호",
    "manufacturer": "퍼스트산업개발",
    "purchaseDate": "2019-03-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "건물-005",
    "equipmentNo": "PM-7",
    "name": "스탠드 에어콘 1호",
    "manufacturer": "퍼스트산업개발",
    "purchaseDate": "2019-03-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "건물-005",
    "equipmentNo": "PM-8",
    "name": "스탠드 에어콘 2호",
    "manufacturer": "퍼스트산업개발",
    "purchaseDate": "2019-03-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "시설장치-002",
    "equipmentNo": "PM-9",
    "name": "Air COMPRESSOR",
    "manufacturer": "ATLAS COPCO",
    "purchaseDate": "2019-03-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "PM-10",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "NEWEAR",
    "purchaseDate": "2019-04-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "Pre-Formation",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "PM-11",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "NEWEAR",
    "purchaseDate": "2019-04-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "Main-Formation",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "PM-12",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "NEWEAR",
    "purchaseDate": "2019-04-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "Grading",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "PM-13",
    "name": "60L Convention Oven(OF-02GW)",
    "manufacturer": "Jeio Tech",
    "purchaseDate": "2019-04-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "시설장치-001",
    "equipmentNo": "PM-14",
    "name": "흡착탑&스크라바 및 덕트",
    "manufacturer": "남양 E&C",
    "purchaseDate": "2019-05-03",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-029",
    "equipmentNo": "PM-15",
    "name": "Folding Module",
    "manufacturer": "㈜피토",
    "purchaseDate": "2019-05-03",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-031",
    "equipmentNo": "PM-16",
    "name": "공침반응기",
    "manufacturer": "케이엠텍",
    "purchaseDate": "2019-05-03",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-020",
    "equipmentNo": "PM-17",
    "name": "약품주입스키드",
    "manufacturer": "프로미넌트코리아㈜",
    "purchaseDate": "2019-05-03",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-017",
    "equipmentNo": "PM-18",
    "name": "waterfall RU100P(워터포인트)",
    "manufacturer": "Water point",
    "purchaseDate": "2019-05-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-033",
    "equipmentNo": "PM-19",
    "name": "Pick-up & Place Machine",
    "manufacturer": "㈜미디어테크",
    "purchaseDate": "2019-05-08",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-001",
    "equipmentNo": "PM-20",
    "name": "EV EL Filling",
    "manufacturer": "㈜에스엔에프",
    "purchaseDate": "2019-05-17",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-019",
    "equipmentNo": "PM-21",
    "name": "5L powder mixer(케이엠텍)",
    "manufacturer": "KM TECH",
    "purchaseDate": "2019-05-17",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-024",
    "equipmentNo": "PM-22",
    "name": "충방전기(5V/1000A급)YBS 7100DP",
    "manufacturer": "유양",
    "purchaseDate": "2019-05-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-021",
    "equipmentNo": "PM-23",
    "name": "EURO Stacking Machine",
    "manufacturer": "㈜이노메트리",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": "전극",
    "assetNo": "기계장치-004",
    "equipmentNo": "PM-24",
    "name": "Planetary Disper Mixer 300L",
    "manufacturer": "㈜신일분산기",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": "전극",
    "assetNo": "기계장치-003",
    "equipmentNo": "PM-25",
    "name": "Planetary Disper Mixer 50L",
    "manufacturer": "㈜T S I",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-005",
    "equipmentNo": "PM-26",
    "name": "Coating System",
    "manufacturer": "㈜에이프로",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-007",
    "equipmentNo": "PM-27",
    "name": "Roll pressing M/C",
    "manufacturer": "씨아이에스주식회사",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-28",
    "name": "Stacking M/C(중고장비)",
    "manufacturer": "mPLUS",
    "purchaseDate": "2019-05-23",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-009",
    "equipmentNo": "PM-29",
    "name": "Automatic Blanking Machine",
    "manufacturer": "A-PRO",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-022",
    "equipmentNo": "PM-30",
    "name": "Fiber Laser Marking System(이비기술)",
    "manufacturer": "㈜이비기술",
    "purchaseDate": "2019-05-29",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": "전극",
    "assetNo": "기계장치-034",
    "equipmentNo": "PM-31",
    "name": "Binder Mixer 150L",
    "manufacturer": "㈜신일분산기",
    "purchaseDate": "2019-06-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": "전극",
    "assetNo": "기계장치-035",
    "equipmentNo": "PM-32",
    "name": "Planetary Disper Mixer 20L",
    "manufacturer": "㈜신일분산기",
    "purchaseDate": "2019-06-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "시설장치-003",
    "equipmentNo": "PM-33",
    "name": "집진기(SDPC-2000)",
    "manufacturer": "SHIN-YONG ENG",
    "purchaseDate": "2019-06-11",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "PM-34",
    "name": "Forced Convection Oven 151L(제이오텍)",
    "manufacturer": "Jeio Tech",
    "purchaseDate": "2019-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "PM-35",
    "name": "Forced convection Oven(제이오텍)",
    "manufacturer": "Jeio Tech",
    "purchaseDate": "2019-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "PM-36",
    "name": "Vacuum Oven set(제이오텍)",
    "manufacturer": "Jeio Tech",
    "purchaseDate": "2019-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "PM-37",
    "name": "Vacuum Oven set(제이오텍)",
    "manufacturer": "Jeio Tech",
    "purchaseDate": "2019-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-033",
    "equipmentNo": "PM-38",
    "name": "Pre welding machine",
    "manufacturer": "㈜미디어테크",
    "purchaseDate": "2019-07-17",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-033",
    "equipmentNo": "PM-39",
    "name": "Tab welding Machine",
    "manufacturer": "㈜미디어테크",
    "purchaseDate": "2019-07-17",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-033",
    "equipmentNo": "PM-40",
    "name": "Electrode Punching Machine",
    "manufacturer": "㈜미디어테크",
    "purchaseDate": "2019-07-17",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-033",
    "equipmentNo": "PM-41",
    "name": "Wetting machine",
    "manufacturer": "㈜미디어테크",
    "purchaseDate": "2019-07-17",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-42",
    "name": "Tab Welding Machine(원통형)(+)",
    "manufacturer": "테크랜드",
    "purchaseDate": "2019-07-17",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "비품-019",
    "equipmentNo": "PM-43",
    "name": "초음파 세척기",
    "manufacturer": "크린온",
    "purchaseDate": "2019-08-10",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-032",
    "equipmentNo": "PM-44",
    "name": "중대형 각형 배터리 레이저 용접기(휴비스)",
    "manufacturer": "TRUMPF",
    "purchaseDate": "2019-08-23",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-039",
    "equipmentNo": "PM-45",
    "name": "슬리팅기(씨아이에스)",
    "manufacturer": "씨아이에스주식회사",
    "purchaseDate": "2019-09-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-041",
    "equipmentNo": "PM-46",
    "name": "전기로(아론케이)",
    "manufacturer": "Aaron",
    "purchaseDate": "2019-10-31",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-040",
    "equipmentNo": "PM-47",
    "name": "Vacuum Oven 1,573L (아론케이)",
    "manufacturer": "Aaron",
    "purchaseDate": "2019-10-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-029",
    "equipmentNo": "PM-48",
    "name": "can insert설비(피토)",
    "manufacturer": "㈜피토",
    "purchaseDate": "2019-12-18",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-062",
    "equipmentNo": "PM-49",
    "name": "방폭챔버 (듀오콤) (2)",
    "manufacturer": "DOCOM",
    "purchaseDate": "2020-01-17",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-069",
    "equipmentNo": "PM-50",
    "name": "Top, Side Sealing Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-01-27",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-066",
    "equipmentNo": "PM-51",
    "name": "El filling Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-03-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-067",
    "equipmentNo": "PM-52",
    "name": "Degas, Ball Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-03-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-068",
    "equipmentNo": "PM-53",
    "name": "Notching Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-03-31",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-070",
    "equipmentNo": "PM-54",
    "name": "V-sealing Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-03-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-071",
    "equipmentNo": "PM-55",
    "name": "Forming Machine",
    "manufacturer": "유진테크놀로지",
    "purchaseDate": "2021-03-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-072",
    "equipmentNo": "PM-56",
    "name": "Cell Hot Press",
    "manufacturer": "스마트 유압기계",
    "purchaseDate": "2021-12-14",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-57",
    "name": "Tab Welding Machine",
    "manufacturer": "테크랜드",
    "purchaseDate": "2022-12-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-58",
    "name": "Swaging Machine",
    "manufacturer": "테크랜드",
    "purchaseDate": "2022-12-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-59",
    "name": "Beading Machine",
    "manufacturer": "테크랜드",
    "purchaseDate": "2022-12-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-60",
    "name": "El filling Machine(원통형)",
    "manufacturer": "테크랜드",
    "purchaseDate": "2022-12-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-074",
    "equipmentNo": "PM-61",
    "name": "Sizing ＆ Crimping Machine",
    "manufacturer": "테크랜드",
    "purchaseDate": "2022-12-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "PM-62",
    "name": "Part for Winding Machine",
    "manufacturer": "코엠",
    "purchaseDate": "2022-12-09",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "시설장치-009",
    "equipmentNo": "PM-63",
    "name": "옥외 리프트 설비",
    "manufacturer": "청룡운반기계",
    "purchaseDate": "2020-07-17",
    "grade": "B",
    "maintenanceMethod": "사후",
    "remark": "유휴설비",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "생산",
    "processType": null,
    "assetNo": "기계장치-075",
    "equipmentNo": "PM-64",
    "name": "항온챔버",
    "manufacturer": "비긴테크",
    "purchaseDate": "2022-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-018",
    "equipmentNo": "DM-01",
    "name": "5V200A16CH 충방전기",
    "manufacturer": "ETH",
    "purchaseDate": "2019-05-14",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 미디어테크",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-016",
    "equipmentNo": "DM-02",
    "name": "X-ray 설비",
    "manufacturer": "자비스",
    "purchaseDate": "2019-05-23",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-025",
    "equipmentNo": "DM-03",
    "name": "pH 미터",
    "manufacturer": "메틀러토레도",
    "purchaseDate": "2019-05-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-023",
    "equipmentNo": "DM-04",
    "name": "수분분석기",
    "manufacturer": "메틀러토레도",
    "purchaseDate": "2019-05-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-026",
    "equipmentNo": "DM-05",
    "name": "Temp. & Humid. Chamber",
    "manufacturer": "제이오텍",
    "purchaseDate": "2019-06-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "DM-06",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2019-08-09",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "DM-07",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2019-08-09",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-037",
    "equipmentNo": "DM-08",
    "name": "5V 50A 224CH 충방전기",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2019-08-09",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "공구와기구-015",
    "equipmentNo": "DM-09",
    "name": "만능재료시험기 10Tonf 외 그립5종",
    "manufacturer": "티엔돌프",
    "purchaseDate": "2019-09-02",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-052",
    "equipmentNo": "DM-10",
    "name": "Planetary centrifugal Mixer(1)",
    "manufacturer": "THINKY",
    "purchaseDate": "2019-11-27",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-045",
    "equipmentNo": "DM-11",
    "name": "항온챔버",
    "manufacturer": "HANGIL",
    "purchaseDate": "2019-12-12",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 라움비티",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-030",
    "equipmentNo": "DM-12",
    "name": "Hot Rolling Machine roll press",
    "manufacturer": "MTI",
    "purchaseDate": "2019-12-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-045",
    "equipmentNo": "DM-13",
    "name": "5V 100mA 32CH 코인셀충방전기",
    "manufacturer": "원아테크",
    "purchaseDate": "2020-01-31",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "DM-14",
    "name": "멀티자력식교반기",
    "manufacturer": "나비엠알오",
    "purchaseDate": "2020-02-06",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-047",
    "equipmentNo": "DM-15",
    "name": "방폭챔버",
    "manufacturer": "듀오콤",
    "purchaseDate": "2020-02-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-060",
    "equipmentNo": "DM-16",
    "name": "방폭챔버",
    "manufacturer": "듀오콤",
    "purchaseDate": "2020-02-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-061",
    "equipmentNo": "DM-17",
    "name": "방폭챔버",
    "manufacturer": "듀오콤",
    "purchaseDate": "2020-02-19",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "공구와기구-038",
    "equipmentNo": "DM-18",
    "name": "Battery Hitester",
    "manufacturer": "히오키",
    "purchaseDate": "2020-02-24",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-048",
    "equipmentNo": "DM-19",
    "name": "5V 600A 16CH 충방전기",
    "manufacturer": "피앤이솔루션",
    "purchaseDate": "2020-02-26",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-049",
    "equipmentNo": "DM-20",
    "name": "5V 600A 16CH 충방전기",
    "manufacturer": "피앤이솔루션",
    "purchaseDate": "2020-02-26",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-052",
    "equipmentNo": "DM-21",
    "name": "Planetary centrifugal Mixer(2)",
    "manufacturer": "THINKY",
    "purchaseDate": "2020-04-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-053",
    "equipmentNo": "DM-22",
    "name": "항온챔버",
    "manufacturer": "HANGIL",
    "purchaseDate": "2020-04-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 라움비티",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-057",
    "equipmentNo": "DM-23",
    "name": "항온챔버",
    "manufacturer": "HANGIL",
    "purchaseDate": "2020-04-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 라움비티",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-050",
    "equipmentNo": "DM-24",
    "name": "5V 100mA 32CH 코인셀충방전기",
    "manufacturer": "원아테크",
    "purchaseDate": "2020-04-29",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-054",
    "equipmentNo": "DM-25",
    "name": "5V 100mA 32CH 코인셀충방전기",
    "manufacturer": "원아테크",
    "purchaseDate": "2020-04-29",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "DM-26",
    "name": "Vortex mixer",
    "manufacturer": "DAIHAN Scientific",
    "purchaseDate": "2020-06-11",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 제이상사",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-063",
    "equipmentNo": "DM-27",
    "name": "5V 100mA 48CH 코인셀충방전기",
    "manufacturer": "원아테크",
    "purchaseDate": "2020-07-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-063",
    "equipmentNo": "DM-28",
    "name": "5V 100mA 48CH 코인셀충방전기",
    "manufacturer": "원아테크",
    "purchaseDate": "2020-07-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-064",
    "equipmentNo": "DM-29",
    "name": "항온챔버",
    "manufacturer": "뉴런핏",
    "purchaseDate": "2020-07-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 마르스",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-31",
    "name": "방폭챔버",
    "manufacturer": "SANWOOD",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 뉴웨어",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-32",
    "name": "방폭챔버",
    "manufacturer": "SANWOOD",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 뉴웨어",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-33",
    "name": "방폭챔버",
    "manufacturer": "SANWOOD",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "구매처 : 뉴웨어",
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-34",
    "name": "CT-4008T-5V6A-S1 충방전기",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-35",
    "name": "온도센서",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": "기계장치-073",
    "equipmentNo": "DM-36",
    "name": "CT-4008T-5V20A-A1 충방전기",
    "manufacturer": "뉴웨어",
    "purchaseDate": "2022-06-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "DM-37",
    "name": "교반기",
    "manufacturer": "IKA",
    "purchaseDate": null,
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "DM-38",
    "name": "마이크로 피펫",
    "manufacturer": "NICHIRYO",
    "purchaseDate": null,
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "개발",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "DM-39",
    "name": "마이크로 피펫",
    "manufacturer": "NICHIRYO",
    "purchaseDate": null,
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": null,
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-01",
    "name": "클램프 미터(AMP-330)",
    "manufacturer": "AMPROBE",
    "purchaseDate": "2019-04-22",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "전류측정기",
    "deviceNo": "170301399",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-02",
    "name": "디지털멀티미터(AM-570)",
    "manufacturer": "AMPROBE",
    "purchaseDate": "2019-04-22",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "DMM",
    "deviceNo": "161204687",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-03",
    "name": "Paperless recorder 및 유틸리티",
    "manufacturer": "요코가와",
    "purchaseDate": "2019-04-24",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "전압, 온도 기록기",
    "deviceNo": "S5UC12088",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-04",
    "name": "절연 저항 시험기(3154)",
    "manufacturer": "히오키코리아",
    "purchaseDate": "2019-05-03",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "110818684",
    "calibrationDate": "2020-02-10",
    "nextCalibrationDate": "2021-02-10",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-05",
    "name": "절연 저항 시험기(ST5520)",
    "manufacturer": "히오키코리아",
    "purchaseDate": "2019-05-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "AC-IR",
    "deviceNo": "190208414",
    "calibrationDate": "2020-02-10",
    "nextCalibrationDate": "2021-02-10",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-06",
    "name": "G20-14-113(그라인드 게이지)",
    "manufacturer": "PK Laboratory Company",
    "purchaseDate": "2019-05-09",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "Grind gauge",
    "deviceNo": "S380930",
    "calibrationDate": "2020-02-12",
    "nextCalibrationDate": "2021-02-12",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-07",
    "name": "버니어켈리퍼스(0~150)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "B18288156",
    "calibrationDate": "2020-02-11",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-08",
    "name": "버니어켈리퍼스(0~200)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "A18188031",
    "calibrationDate": "2020-02-11",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-09",
    "name": "Micrometer(MDC-25PX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "C",
    "maintenanceMethod": "폐기",
    "remark": "폐기(21.02.02)",
    "deviceNo": "25237094",
    "calibrationDate": "2020-02-11",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-10",
    "name": "Micrometer(MDC-25PX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "C",
    "maintenanceMethod": "폐기예정",
    "remark": "고장상태",
    "deviceNo": "63349210",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-11",
    "name": "Micrometer(MDC-25PX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "63349176",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-12",
    "name": "Micrometer(MDC-25PX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "63349187",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-13",
    "name": "디지털 게이지(두께 측정기)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "17232740",
    "calibrationDate": "2020-02-11",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-14",
    "name": "디지털 게이지(두께 측정기)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "17220997",
    "calibrationDate": "2020-02-11",
    "nextCalibrationDate": "2021-02-11",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-15",
    "name": "틈새게이지",
    "manufacturer": "BLUETEC",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "035740",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-16",
    "name": "틈새게이지",
    "manufacturer": "BLUETEC",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "035741",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-17",
    "name": "틈새게이지",
    "manufacturer": "BLUETEC",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "035742",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-18",
    "name": "틈새게이지",
    "manufacturer": "BLUETEC",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "035743",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-19",
    "name": "틈새게이지",
    "manufacturer": "BLUETEC",
    "purchaseDate": "2019-05-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "035744",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-009",
    "equipmentNo": "TM-20",
    "name": "전자저울(MC-1000)",
    "manufacturer": "AND",
    "purchaseDate": "2019-05-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "전자저울",
    "deviceNo": "14593530",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-007",
    "equipmentNo": "TM-21",
    "name": "전자저울(GX-1003A)",
    "manufacturer": "AND",
    "purchaseDate": "2019-05-20",
    "grade": "B",
    "maintenanceMethod": "사전",
    "remark": "전자저울(무게 측정 오차)",
    "deviceNo": "T2002746",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-22",
    "name": "전자저울(DB-1/1H)",
    "manufacturer": "CAS",
    "purchaseDate": "2019-05-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "전자저울",
    "deviceNo": "CQT1219",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-23",
    "name": "전자저울(DB-1/1H)",
    "manufacturer": "CAS",
    "purchaseDate": "2019-05-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "전자저울",
    "deviceNo": "CQT1170",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-011",
    "equipmentNo": "TM-24",
    "name": "DV2T(점도계)",
    "manufacturer": "BROOKFIELD",
    "purchaseDate": "2019-05-20",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "점도측정기",
    "deviceNo": "86004006",
    "calibrationDate": "2019-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-25",
    "name": "방사능측정기",
    "manufacturer": "S.E. International",
    "purchaseDate": "2019-06-04",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "41096",
    "calibrationDate": "2020-01-20",
    "nextCalibrationDate": "2021-01-20",
    "calibrationAgency": "나우㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-017",
    "equipmentNo": "TM-26",
    "name": "파워미터(WT333E)",
    "manufacturer": "YOKOGAWA",
    "purchaseDate": "2019-06-28",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "파워미터",
    "deviceNo": "C3VA28008E",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "한국산업기술시험원"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-019",
    "equipmentNo": "TM-27",
    "name": "열화상 카메라(Ti300)",
    "manufacturer": "Fluke",
    "purchaseDate": "2019-06-28",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "열화상 온도측정기",
    "deviceNo": "18110176",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-28",
    "name": "DC Load(PlZ1205W)",
    "manufacturer": "KIKUSUI",
    "purchaseDate": "2019-08-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "방전기",
    "deviceNo": "ZA003817",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-29",
    "name": "DC Powersupply(PAT60-133T)",
    "manufacturer": "KIKUSUI",
    "purchaseDate": "2019-08-05",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "충전기",
    "deviceNo": "UF2056E",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": "공구와기구-004",
    "equipmentNo": "TM-30",
    "name": "파티클카운터(DT-9880)",
    "manufacturer": "CEM",
    "purchaseDate": "2019-11-12",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "191005666",
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-31",
    "name": "Battery Hitester(BT3562)",
    "manufacturer": "히오키코리아",
    "purchaseDate": "2020-02-24",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "191111278",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-32",
    "name": "전자저울(HR-250AZ)",
    "manufacturer": "AND",
    "purchaseDate": "2020-02-06",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "16023428",
    "calibrationDate": "2025-09-29",
    "nextCalibrationDate": "2021-01-21",
    "calibrationAgency": "(주)코아테크코리아"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-33",
    "name": "온/습도계_41494604",
    "manufacturer": "TESTO",
    "purchaseDate": "2020-05-07",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "온/습도계",
    "deviceNo": "41494604",
    "calibrationDate": "2020-04-22",
    "nextCalibrationDate": "2021-04-22",
    "calibrationAgency": "디와이캘텍㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-34",
    "name": "온/습도계_41494606",
    "manufacturer": "TESTO",
    "purchaseDate": "2020-05-07",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "온/습도계",
    "deviceNo": "41494606",
    "calibrationDate": "2020-04-22",
    "nextCalibrationDate": "2021-04-22",
    "calibrationAgency": "디와이캘텍㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-35",
    "name": "온/습도계_41494607",
    "manufacturer": "TESTO",
    "purchaseDate": "2020-05-07",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "온/습도계",
    "deviceNo": "41494607",
    "calibrationDate": "2020-04-22",
    "nextCalibrationDate": "2021-04-22",
    "calibrationAgency": "디와이캘텍㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-36",
    "name": "내전압시험기(19052)",
    "manufacturer": "CHROMA",
    "purchaseDate": "2020-06-16",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "내전압시험기",
    "deviceNo": "190520001247",
    "calibrationDate": "2020-07-21",
    "nextCalibrationDate": "2021-07-21",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-37",
    "name": "전자저울(AX324KR)",
    "manufacturer": "OHAUS",
    "purchaseDate": "2020-07-08",
    "grade": "C",
    "maintenanceMethod": "폐기",
    "remark": "폐기",
    "deviceNo": "B915502201",
    "calibrationDate": "2020-07-20",
    "nextCalibrationDate": "2021-07-20",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-38",
    "name": "디지털온습도계(TH210-HODP 150-R)",
    "manufacturer": "KIMO",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": "노점측정기",
    "deviceNo": "2F180829588",
    "calibrationDate": "2020-08-06",
    "nextCalibrationDate": "2021-08-06",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-39",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703662",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-40",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703658",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-41",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703510",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-42",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "C",
    "maintenanceMethod": "폐기",
    "remark": "폐기(21.02.02)",
    "deviceNo": "180703640",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-43",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703846",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-44",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703814",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-45",
    "name": "디지털온습도계(HS30TR)",
    "manufacturer": "HANSUNG",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "180703664",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-46",
    "name": "온습도계",
    "manufacturer": "-",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "2002924",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-47",
    "name": "온습도계",
    "manufacturer": "-",
    "purchaseDate": "2020-07-10",
    "grade": "C",
    "maintenanceMethod": "폐기",
    "remark": "(폐기)1층 사용",
    "deviceNo": "2002925",
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-48",
    "name": "온습도계",
    "manufacturer": "-",
    "purchaseDate": "2020-07-10",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "2002926",
    "calibrationDate": "2020-07-31",
    "nextCalibrationDate": "2021-07-31",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-49",
    "name": "DC Load(PLZ303W)",
    "manufacturer": "KIKUSUI",
    "purchaseDate": "2020-08-11",
    "grade": "A",
    "maintenanceMethod": null,
    "remark": null,
    "deviceNo": "EM001130",
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-50",
    "name": "DC Powersupply(TSP20015)",
    "manufacturer": "스마트파워",
    "purchaseDate": "2020-08-21",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "45S20015176",
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-51",
    "name": "수분측정기(목재)-HM50",
    "manufacturer": "KIMO",
    "purchaseDate": "2020-09-08",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "1P190775023",
    "calibrationDate": "2020-09-02",
    "nextCalibrationDate": "2021-09-02",
    "calibrationAgency": "코리아인스트루먼트㈜"
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-52",
    "name": "Micromiter(MDC-25SX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2021-01-11",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "66728133",
    "calibrationDate": "2025-10-13",
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-53",
    "name": "Micromiter(SPM2-25MX)",
    "manufacturer": "Mitutoyo",
    "purchaseDate": "2021-02-03",
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "-",
    "calibrationDate": "2025-10-13",
    "nextCalibrationDate": null,
    "calibrationAgency": null
  },
  {
    "category": "측정",
    "processType": null,
    "assetNo": null,
    "equipmentNo": "TM-54",
    "name": "적외선 온도 측정기(UT300B)",
    "manufacturer": "UNI-T",
    "purchaseDate": null,
    "grade": "A",
    "maintenanceMethod": "사전",
    "remark": null,
    "deviceNo": "H150903115",
    "calibrationDate": null,
    "nextCalibrationDate": null,
    "calibrationAgency": null
  }
] as const;
