// 자동 생성된 시드 파일 — export-material-seed.ts 로 생성
import { MaterialOrigin, MaterialProcess, MaterialPurpose } from '../../common/enums/material.enum';

export const MATERIAL_SEED_DATA = [
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "PVDF Solef 5130",
    "spec": "20kg/bag",
    "lotNo": "TAOE22148G",
    "company": "타이포리머",
    "origin": "해외",
    "unit": "kg",
    "price": "80000.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "PVDF Solef 5130",
    "spec": "20kg/bag",
    "lotNo": "TAOE23142A",
    "company": "타이폴리머",
    "origin": "해외",
    "unit": "kg",
    "price": "80000.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "PVDF Solef 5130",
    "spec": "20kg/bag",
    "lotNo": "TAOE23179T",
    "company": "타이폴리머",
    "origin": "해외",
    "unit": "kg",
    "price": "60000.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "PVDF Solef 5130",
    "spec": "2.5kg/bag",
    "lotNo": "CES190005A",
    "company": "타이폴리머",
    "origin": "해외",
    "unit": "kg",
    "price": "80000.00",
    "note": "",
    "stock": 6
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "PVDF Solef 5130",
    "spec": "20kg/bag",
    "lotNo": "TAOE24033A",
    "company": "타이폴리머",
    "origin": "해외",
    "unit": "kg",
    "price": "60000.00",
    "note": null,
    "stock": 14
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "생산",
    "name": "NEOFLON VT-475",
    "spec": "35kg/bag",
    "lotNo": "AI00102427",
    "company": "다이킨코리아",
    "origin": "해외",
    "unit": "kg",
    "price": "155130.00",
    "note": null,
    "stock": 35
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "PVdF",
    "purpose": "개발",
    "name": "KF polymer W#9100",
    "spec": "20kg/bag",
    "lotNo": "8Y972",
    "company": "KUREHA",
    "origin": "해외",
    "unit": "kg",
    "price": "50000.00",
    "note": null,
    "stock": 20
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "SBR",
    "purpose": "개발",
    "name": "A-401D",
    "spec": "20kg/drum",
    "lotNo": "33122102719",
    "company": "대흥케미칼(한솔)",
    "origin": "국내",
    "unit": "kg",
    "price": "65000.00",
    "note": null,
    "stock": 15
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "CMC",
    "purpose": "생산",
    "name": "MAC500",
    "spec": "20kg/bag",
    "lotNo": null,
    "company": "SUNROSE(도요타상사)",
    "origin": "해외",
    "unit": "kg",
    "price": "70000.00",
    "note": null,
    "stock": 15
  },
  {
    "process": "전극",
    "category": "바인더",
    "type": "CMC",
    "purpose": "개발",
    "name": "MAC800",
    "spec": "20kg/bag",
    "lotNo": null,
    "company": "SUNROSE(도요타상사)",
    "origin": "해외",
    "unit": "kg",
    "price": "70000.00",
    "note": null,
    "stock": 16
  },
  {
    "process": "전극",
    "category": "도전재",
    "type": "Carbon black",
    "purpose": "생산",
    "name": "Super-P-Li",
    "spec": "7.5kg/bag",
    "lotNo": "841D0212",
    "company": "IMERYS(케이비코퍼레이션)",
    "origin": "해외",
    "unit": "kg",
    "price": "20000.00",
    "note": null,
    "stock": 5
  },
  {
    "process": "전극",
    "category": "도전재",
    "type": "CNT",
    "purpose": "생산",
    "name": "CN-04Y",
    "spec": "20kg/drum",
    "lotNo": "ANP-221219",
    "company": "나노신소재",
    "origin": "국내",
    "unit": "kg",
    "price": "41000.00",
    "note": "MWCNT",
    "stock": 0
  },
  {
    "process": "전극",
    "category": "용매",
    "type": "NMP",
    "purpose": "생산",
    "name": "NMP",
    "spec": "200kg/drum",
    "lotNo": "NMP-H-250716",
    "company": "재원인더스트리",
    "origin": "국내",
    "unit": "kg",
    "price": "5000.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "용매",
    "type": "NMP",
    "purpose": "생산",
    "name": "NMP",
    "spec": "200kg/drum",
    "lotNo": "NMP-H-251020",
    "company": "재원인더스트리",
    "origin": "국내",
    "unit": "kg",
    "price": "5000.00",
    "note": null,
    "stock": 193
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "15DP",
    "spec": "20kg/bag",
    "lotNo": "ZBGSL-15DP-22091602",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "54643.00",
    "note": null,
    "stock": 10
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "15DP",
    "spec": "10kg/bag",
    "lotNo": "ZBGSL-15DP-22041602",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "54643.00",
    "note": null,
    "stock": 6
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "15DP",
    "spec": "15kg/bag",
    "lotNo": "ZBGSL-15DP-22121802",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "54643.00",
    "note": null,
    "stock": 12
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "15DP",
    "spec": "5kg/bag",
    "lotNo": "ZBGSL-15DP-23042001",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "54643.00",
    "note": null,
    "stock": 4
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "15DP",
    "spec": "20kg/bag",
    "lotNo": "GSL-15DP-24050502",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "36540.00",
    "note": null,
    "stock": 13
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "CT19",
    "spec": "20kg/bag",
    "lotNo": "DC21K01B",
    "company": "코스모신소재",
    "origin": "국내",
    "unit": "kg",
    "price": "54643.00",
    "note": null,
    "stock": 20
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "LCO",
    "purpose": "생산",
    "name": "CTX19",
    "spec": "20kg/bag",
    "lotNo": "DC21K02B",
    "company": "코스모신소재",
    "origin": "국내",
    "unit": "kg",
    "price": "94941.00",
    "note": null,
    "stock": 25
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM622",
    "purpose": "생산",
    "name": "ME-6E",
    "spec": "20kg/bag",
    "lotNo": "JS-ME6E-22121503",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "79947.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM622",
    "purpose": "생산",
    "name": "ME-6E",
    "spec": "20kg/bag",
    "lotNo": "JS-ME6E-24081403",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "40074.00",
    "note": null,
    "stock": 5
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM622",
    "purpose": "개발",
    "name": "ME-6E2XP",
    "spec": "10kg/bag",
    "lotNo": "CZ-ME6E2XP-24051401",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": null,
    "note": null,
    "stock": 10
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM613",
    "purpose": "개발",
    "name": "ME-6SC2",
    "spec": "20kg/bag",
    "lotNo": "CZ-ME6SC2-22122703",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "79947.00",
    "note": null,
    "stock": 7
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM613",
    "purpose": "개발",
    "name": "ME-6SC5",
    "spec": "20kg/bag",
    "lotNo": "CZ-ME6SC5-24053001",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": null,
    "note": null,
    "stock": 20
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM622",
    "purpose": "생산",
    "name": "NCM-622",
    "spec": "20kg/bag",
    "lotNo": "NCM622-221007-01",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "65000.00",
    "note": null,
    "stock": 6
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM622",
    "purpose": "생산",
    "name": "NCM-622",
    "spec": "20kg/bag",
    "lotNo": "NCM622-0001-30",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "65000.00",
    "note": null,
    "stock": 65
  },
  {
    "process": "전극",
    "category": "양극재",
    "type": "NCM811",
    "purpose": "개발",
    "name": "ME-8E3S",
    "spec": "20kg/bag",
    "lotNo": "CZ-ME8E3S-25100503",
    "company": "EASPRING",
    "origin": "해외",
    "unit": "kg",
    "price": "50918.00",
    "note": null,
    "stock": 18
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "생산",
    "name": "KP-T2",
    "spec": "20kg/bag",
    "lotNo": "TE010-230211",
    "company": "KEDA",
    "origin": "해외",
    "unit": "kg",
    "price": "49294.00",
    "note": null,
    "stock": 69
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "생산",
    "name": "KP-T2",
    "spec": "25kg/bag",
    "lotNo": "TE011-231011-1",
    "company": "KEDA",
    "origin": "해외",
    "unit": "kg",
    "price": "45429.00",
    "note": null,
    "stock": 25
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "생산",
    "name": "LTO-T30-D8",
    "spec": "20kg/bag",
    "lotNo": "PT221007-01",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "62000.00",
    "note": null,
    "stock": 20
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "생산",
    "name": "T2",
    "spec": "25kg/bag",
    "lotNo": "TE011-250401",
    "company": "BRT",
    "origin": "해외",
    "unit": "kg",
    "price": "46891.00",
    "note": null,
    "stock": 16
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "개발",
    "name": "LTO-GEN4",
    "spec": "15kg/bag",
    "lotNo": "AT80479",
    "company": "Altairnano",
    "origin": "해외",
    "unit": "kg",
    "price": "90000.00",
    "note": null,
    "stock": 30
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "LTO",
    "purpose": "개발",
    "name": "미정",
    "spec": "20kg/bag",
    "lotNo": null,
    "company": "역신",
    "origin": "해외",
    "unit": "kg",
    "price": "70000.00",
    "note": null,
    "stock": 5
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "천연흑연",
    "purpose": "개발",
    "name": "PAS-A1",
    "spec": "10kg/bag",
    "lotNo": "A200219002",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "11025.00",
    "note": null,
    "stock": 1
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "천연흑연",
    "purpose": "개발",
    "name": "PAS-A1",
    "spec": "20kg/bag",
    "lotNo": "A210718001-01",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "11025.00",
    "note": null,
    "stock": 4
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "천연흑연",
    "purpose": "생산",
    "name": "PAS-C2",
    "spec": "20kg/bag",
    "lotNo": "00822110055B07J",
    "company": "포스코케미칼",
    "origin": "국내",
    "unit": "kg",
    "price": "20000.00",
    "note": null,
    "stock": 23
  },
  {
    "process": "전극",
    "category": "음극재",
    "type": "인조흑연",
    "purpose": "생산",
    "name": "G56",
    "spec": "25kg/bag",
    "lotNo": "220605",
    "company": "지천테크놀로지",
    "origin": "해외",
    "unit": "kg",
    "price": "17658.00",
    "note": null,
    "stock": 14
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(12㎛ x 230㎜)",
    "spec": "12㎛ x 230㎜ x 2,000m/roll",
    "lotNo": "C2E4100006-21",
    "company": "롯데인프라셀",
    "origin": "국내",
    "unit": "m",
    "price": "107.00",
    "note": null,
    "stock": 6000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(10㎛ x 100㎜)",
    "spec": "10㎛ x 100㎜ x 1,200m/roll",
    "lotNo": "PW0566-T0010",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "77.00",
    "note": null,
    "stock": 1200
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(12㎛ x 160㎜)",
    "spec": "12㎛ x 160㎜ x 1,000m/roll",
    "lotNo": "PW2272-T0020",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "96.00",
    "note": null,
    "stock": 3000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(12㎛ x 230㎜)",
    "spec": "12㎛ x 230㎜ x 1,000m/roll",
    "lotNo": "PW0256-T0006",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "134.00",
    "note": null,
    "stock": 2000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(12㎛ x 220㎜)",
    "spec": "12㎛ x 220㎜ x 1,000m/roll",
    "lotNo": "PW3074-T004~08",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "129.00",
    "note": null,
    "stock": 4000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(12㎛ x 105㎜)",
    "spec": "12㎛ x 105㎜ x 1,000m/roll",
    "lotNo": "PW3074-T009-13",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "61.00",
    "note": null,
    "stock": 4800
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(10㎛ x 230㎜)",
    "spec": "10㎛ x 230㎜ x 1,200m/roll",
    "lotNo": "PU0704-T0019",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "825.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "개발",
    "name": "A1050-H18(15㎛ x 160㎜)",
    "spec": "15㎛ x 160㎜ x 2,000m/roll",
    "lotNo": "L193111-067",
    "company": "동일알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": "120.00",
    "note": null,
    "stock": 2000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(10㎛ x 230㎜)",
    "spec": "10㎛ x 230㎜ x 1,200m/roll",
    "lotNo": "PW1769",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": null,
    "note": null,
    "stock": 0
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1050-H18(15㎛ x 230㎜)",
    "spec": "15㎛ x 230㎜ x 2,900m/roll",
    "lotNo": "521-9-70-6-1",
    "company": "동원시스템즈",
    "origin": "국내",
    "unit": "m",
    "price": "220.00",
    "note": "카본코팅",
    "stock": 5800
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Al Foil",
    "purpose": "생산",
    "name": "A1100 H18(15㎛ x 160㎜)",
    "spec": "15㎛ x 160㎜ x 1,200m/roll",
    "lotNo": "PW1653",
    "company": "삼아알루미늄",
    "origin": "국내",
    "unit": "m",
    "price": null,
    "note": null,
    "stock": 1200
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Cu Foil",
    "purpose": "생산",
    "name": "Cu Foil(8㎛ x 320㎜)",
    "spec": "8㎛ x 320㎜ x 1,500m/roll",
    "lotNo": null,
    "company": "경동소재",
    "origin": "국내",
    "unit": "m",
    "price": null,
    "note": null,
    "stock": 3000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Cu Foil",
    "purpose": "생산",
    "name": "Cu Foil(6㎛ x 450㎜)",
    "spec": "6㎛ x 450㎜ x 2,000m/roll",
    "lotNo": null,
    "company": "경동소재",
    "origin": "국내",
    "unit": "m",
    "price": null,
    "note": null,
    "stock": 2000
  },
  {
    "process": "전극",
    "category": "집전체",
    "type": "Cu Foil",
    "purpose": "생산",
    "name": "B-STN(10㎛ x 105㎜)",
    "spec": "10㎛ x 105㎜ x 1,000m/roll",
    "lotNo": "SM3012025091007",
    "company": "SK넥실리스",
    "origin": "국내",
    "unit": "m",
    "price": "258.00",
    "note": null,
    "stock": 0
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "기타",
    "purpose": "개발",
    "name": "분리막(16*112)",
    "spec": "16um x 112mm x 1,000m/roll",
    "lotNo": "CS16112",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "드라이룸",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "원단",
    "purpose": "개발",
    "name": "MS-WPS09",
    "spec": "9um x 182mm x 1,000m/roll",
    "lotNo": "E9S6230831A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "300.00",
    "note": "",
    "stock": 995
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "원단",
    "purpose": "개발",
    "name": "MS-WPS09",
    "spec": "9um x 182mm x 1,000m/roll",
    "lotNo": "E9S623120101A02",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "300.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "원단",
    "purpose": "개발",
    "name": "MS-WPS12",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "E12S6230831A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "300.00",
    "note": "",
    "stock": 995
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "개발",
    "name": "MS-PCS 12E9E1.51.5D",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "E12C1S6231201A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "S12C2S3220906A04",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "328.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "E12C1S6231122A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "328.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "개발",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "E12C1S3241227A03",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "328.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 192mm x 1,000m/roll",
    "lotNo": "E12C1S2250704A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "330.00",
    "note": "",
    "stock": 850
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 192mm x 1,000m/roll",
    "lotNo": "E12C1S2250825A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "330.00",
    "note": "",
    "stock": 3000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 192mm x 1,000m/roll",
    "lotNo": "E12C1S2250829A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "330.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "생산",
    "name": "PCS13E9E22DA5",
    "spec": "13um x 192mm x 1,000m/roll",
    "lotNo": "E13S22412160103",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "442.00",
    "note": "드라이룸",
    "stock": 300
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "생산",
    "name": "PCS13E9E22DA5",
    "spec": "13um x 193mm x 2,000m/roll",
    "lotNo": "E13C1S22050513A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "드라이룸",
    "stock": 500
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "생산",
    "name": "PCS13E9E22DA5",
    "spec": "13um x 196mm x 1,000m/roll",
    "lotNo": "E13C1S3251112A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "125.00",
    "note": "드라이룸",
    "stock": 800
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 66mm x 1,000m/roll",
    "lotNo": "E12C2S1230511A02",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "200.00",
    "note": "",
    "stock": 4000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "생산",
    "name": "PCS18E16E2S",
    "spec": "18um x 196mm x 1,000m/roll",
    "lotNo": "E18C3S3250103A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "드라이룸",
    "stock": 800
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "원단",
    "purpose": "생산",
    "name": "Navitas",
    "spec": "18um x 192mm x 1,000m/roll",
    "lotNo": "PS18192",
    "company": "Celgard",
    "origin": "해외",
    "unit": "m",
    "price": "0.00",
    "note": "드라이룸",
    "stock": 3000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "기타",
    "purpose": "개발",
    "name": "ELC",
    "spec": "13um x 66mm x 1,000m/roll",
    "lotNo": "IS1366",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 4500
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "생산",
    "name": "GPCS13E9E22D",
    "spec": "13um x 66mm x 1,000m/roll",
    "lotNo": "E13S2250910A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "그래핀코팅",
    "stock": 3000
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "단면",
    "purpose": "불용",
    "name": "MS-PCS 12E9S3S",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "PS12182",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "328.00",
    "note": "불용",
    "stock": 1800
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "양면",
    "purpose": "불용",
    "name": "EN 16um",
    "spec": "16um x 112mm x 900m/roll",
    "lotNo": "P1601DG6",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "불용",
    "stock": 5400
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "셀룰로스",
    "purpose": "불용",
    "name": "K32-1050",
    "spec": "25um x 120mm x 300m",
    "lotNo": "1413K010, 0924K010",
    "company": "엠디브로스",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "불용",
    "stock": 600
  },
  {
    "process": "조립",
    "category": "분리막",
    "type": "기타",
    "purpose": "불용",
    "name": "HTDS0903-870",
    "spec": "12um x 182mm x 1,000m/roll",
    "lotNo": "1271",
    "company": "엔텍",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "불용",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "ED-UFC-026A1",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+1%TMSB",
    "lotNo": "SL22-2933",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "Coin cell 전해액",
    "spec": "1.15M LiPF6 in EC/EMC=3/7",
    "lotNo": "SL23-2081",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "ED-UFC-026A1",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+1%TMSB",
    "lotNo": "SL24-2828",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "ED-UFC-026A1",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+1%TMSB",
    "lotNo": "SL25-0819",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1111
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A5",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 5% FEC+1% TMSB",
    "lotNo": "SL24-3943",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A6",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 5% FEC+1% LiTFSI",
    "lotNo": "SL24-3579",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A7",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 3% FEC+0.5% PA800",
    "lotNo": "SL24-3580",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "ED-UHC-010",
    "spec": "1.3M LiPF6 in EC/EMC/DMC=2/1/7+5% FEC+1% LiBOB+1% SN",
    "lotNo": "SL25-3220",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "Navitas",
    "spec": "1.0M LiPF6 in EC/EMC/DMC=25/45/30(w/w)+3% VC",
    "lotNo": "SL25-0272",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-001",
    "spec": "1.0M LiPF6 in EC/EMC/DMC=25/45/30(w/w)+3% VC",
    "lotNo": "SL25-2466",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-002",
    "spec": "0.6M LiPF6+0.6M LiFSI in EC/EMC/DEC=35/55/10(w/w)+1.5% VC+1.5% ESA",
    "lotNo": "SL25-2467",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-003",
    "spec": "1M LiPF6+0.2M LiFSI in EC/EMC/DEC=35/35/30(w/w) +1.5% VC",
    "lotNo": "SL25-2468",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-004",
    "spec": "0.8M LiPF6+0.4M LiFSI in EC/EMC/DEC=30/55/15(w/w) +1.0% VC+1.0% LiBOB+1.5% TMSPi",
    "lotNo": "SL25-2469",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-005",
    "spec": "1.15M LiPF6 in EC/PC/EMC/DEC=30/5/55/10(w/w) +VC/PS/SN=3/1/0.3%",
    "lotNo": "SL25-2470",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-006",
    "spec": "1.15M LiPF6 in EC/EMC/DEC=3/6/1(v/v) +FEC/VC/PS/LiBOB=1/2/2/0.5%",
    "lotNo": "SL25-2471",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "test",
    "stock": 99
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "생산",
    "name": "Electrolyte-001",
    "spec": "1.0M LiPF6 in EC/EMC/DMC=25/45/30(w/w)+3% VC",
    "lotNo": "SL25-3794",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 4
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A5",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 5% FEC+1% TMSB",
    "lotNo": "SL25-3795",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A6",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 5% FEC+1% LiTFSI",
    "lotNo": "SL25-3796",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A7",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 3% FEC+0.5% PA800",
    "lotNo": "SL25-3797",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "전해액",
    "type": "LiPF6",
    "purpose": "개발",
    "name": "ED-UFC-026A8",
    "spec": "1.15M LiPF6 in PC/EP/PP=2/4/4(v/v)+ 5% FEC+0.3% ESA",
    "lotNo": "SL25-3798",
    "company": "동화일렉트로라이트",
    "origin": "국내",
    "unit": "kg",
    "price": "50000.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "개발",
    "name": "CP-153A",
    "spec": "153um * 250mm(필름) x 200m/roll",
    "lotNo": "A4F130101",
    "company": "디아인텍",
    "origin": "국내",
    "unit": "m",
    "price": "1175.00",
    "note": "",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "개발",
    "name": "CP-153A",
    "spec": "153um * 250mm(필름) x 50m/roll",
    "lotNo": "A5A130104",
    "company": "디아인텍",
    "origin": "국내",
    "unit": "m",
    "price": "1175.00",
    "note": "Navitas 출고 동일 제품(Sample)",
    "stock": 0
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "생산",
    "name": "CP-153A",
    "spec": "153um * 400mm(필름) x 100m/roll",
    "lotNo": "A4L230101",
    "company": "디아인텍",
    "origin": "국내",
    "unit": "m",
    "price": "1880.00",
    "note": "",
    "stock": 300
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "생산",
    "name": "BS186A",
    "spec": "186um * 400mm(필름) x 300m/roll",
    "lotNo": "3186 5326050401",
    "company": "SBTL",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "SBTL 파우치 저항 test용(A type)",
    "stock": 279
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "생산",
    "name": "BS186A",
    "spec": "186um * 400mm(필름) x 300m/roll",
    "lotNo": "2686 5418060502",
    "company": "SBTL",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "SBTL 파우치 저항 test용(B type)",
    "stock": 280
  },
  {
    "process": "조립",
    "category": "파우치",
    "type": "CPP",
    "purpose": "생산",
    "name": "BS186A",
    "spec": "186um * 400mm(필름) x 300m/roll",
    "lotNo": "3186 5B18010101",
    "company": "SBTL",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "SBTL 파우치 저항 test용(C type)",
    "stock": 300
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Cu lead tab",
    "purpose": "불용",
    "name": "Cu lead tab",
    "spec": "0.3T*25W-PP8.0*30-44P(H6.0)",
    "lotNo": "211216MIN-02-001",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "중형",
    "stock": 100
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Cu lead tab",
    "purpose": "불용",
    "name": "Cu lead tab",
    "spec": "0.3T x 25W x 44L",
    "lotNo": "YJT-NC210630",
    "company": "유진테크놀로지",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "불용",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Cu lead tab",
    "purpose": "불용",
    "name": "Cu lead tab",
    "spec": "0.3T x 25W x 44L",
    "lotNo": "YJT-NC211012",
    "company": "유진테크놀로지",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "불용",
    "stock": 800
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Al lead tab",
    "purpose": "생산",
    "name": "Al lead tab",
    "spec": "0.3T x 25W x 44L",
    "lotNo": "230816MA",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "ea",
    "price": "300.00",
    "note": "",
    "stock": 1000
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Al lead tab",
    "purpose": "생산",
    "name": "Al lead tab(A1235-H0)",
    "spec": "0.1T × 5W",
    "lotNo": "AL221202-015-L2",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "m",
    "price": "250.00",
    "note": "표면처리有",
    "stock": 1470
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Al lead tab",
    "purpose": "생산",
    "name": "Al lead tab(A1050-H0)",
    "spec": "AL 0.3T x 25W x 44L x FUJI 0.1T x 8W x 30L",
    "lotNo": "AL241010-001",
    "company": "유진테크놀로지",
    "origin": "국내",
    "unit": "ea",
    "price": "618.00",
    "note": "",
    "stock": 64
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Al lead tab",
    "purpose": "생산",
    "name": "Al lead tab(A1050-H0)",
    "spec": "AL-0.3T x 60W x 36L-H5-Q-PO-12W x 70L",
    "lotNo": "EUAT250407K14",
    "company": "엘콤",
    "origin": "국내",
    "unit": "ea",
    "price": "1100.00",
    "note": "",
    "stock": 161
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Ni lead tab",
    "purpose": "생산",
    "name": "Ni lead tab",
    "spec": "0.1T × 4W",
    "lotNo": "220704 15A",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 1722
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Ni lead tab",
    "purpose": "생산",
    "name": "Ni lead tab",
    "spec": "0.1T × 4W",
    "lotNo": "IL014",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "표면처리有",
    "stock": 1545
  },
  {
    "process": "조립",
    "category": "리드탭",
    "type": "Ni lead tab",
    "purpose": "생산",
    "name": "Ni lead tab",
    "spec": "0.1T × 3W",
    "lotNo": "NI221114-013-L1-02-D",
    "company": "신화아이티",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 1200
  },
  {
    "process": "조립",
    "category": "원통형",
    "type": "Can",
    "purpose": "생산",
    "name": "21700 Can",
    "spec": "",
    "lotNo": "IA01",
    "company": "ZHONGRUI",
    "origin": "국내",
    "unit": "ea",
    "price": "551.00",
    "note": "Can&Cap set 단가(1,101원)",
    "stock": 596
  },
  {
    "process": "조립",
    "category": "원통형",
    "type": "Cap",
    "purpose": "생산",
    "name": "21700 Cap",
    "spec": "",
    "lotNo": "IA02",
    "company": "ZHONGRUI",
    "origin": "국내",
    "unit": "ea",
    "price": "551.00",
    "note": "",
    "stock": 807
  },
  {
    "process": "조립",
    "category": "원통형",
    "type": "Insulation sheet",
    "purpose": "생산",
    "name": "절연시트 (+)",
    "spec": "0.3T",
    "lotNo": "IA03",
    "company": "고려이노테크",
    "origin": "국내",
    "unit": "ea",
    "price": "40.00",
    "note": "",
    "stock": 90
  },
  {
    "process": "조립",
    "category": "원통형",
    "type": "Insulation sheet",
    "purpose": "생산",
    "name": "절연시트 (-)",
    "spec": "0.3T",
    "lotNo": "IA04",
    "company": "고려이노테크",
    "origin": "국내",
    "unit": "ea",
    "price": "40.00",
    "note": "",
    "stock": 119
  },
  {
    "process": "조립",
    "category": "원통형",
    "type": "PP film",
    "purpose": "생산",
    "name": "PP film",
    "spec": "0.3T, W70",
    "lotNo": "IA05",
    "company": "고려이노테크",
    "origin": "국내",
    "unit": "roll",
    "price": "0.00",
    "note": "ELC 인슐레이터 원재료",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spacer",
    "purpose": "개발",
    "name": "1.0T",
    "spec": "SUS316L",
    "lotNo": "CA01",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "SUS316L (5종 set 단가 4,000원, 변동)",
    "stock": 15
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spacer",
    "purpose": "개발",
    "name": "1.5T",
    "spec": "",
    "lotNo": "CA02",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "SUS316L (5종 set 단가 4,000원, 변동)",
    "stock": 385
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Gasket",
    "purpose": "개발",
    "name": "PP Gasket",
    "spec": "",
    "lotNo": "CA03",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "Polypropylene (5종 set 단가 4,000원, 변동)",
    "stock": 212
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Case",
    "purpose": "개발",
    "name": "Case",
    "spec": "",
    "lotNo": "CA04",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "SUS316L (5종 set 단가 4,000원, 변동)",
    "stock": 210
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Cap",
    "purpose": "개발",
    "name": "Cap",
    "spec": "",
    "lotNo": "CA05",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "SUS316L (5종 set 단가 4,000원, 변동)",
    "stock": 266
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spring",
    "purpose": "개발",
    "name": "Wave Spring",
    "spec": "",
    "lotNo": "CA06",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "770.00",
    "note": "SUS316L (5종 set 단가 4,000원, 변동)",
    "stock": 166
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Li metal",
    "purpose": "개발",
    "name": "Lithium metal",
    "spec": "0.3T, W39mm, 125g=1pk",
    "lotNo": "CA07",
    "company": "웰코스",
    "origin": "국내",
    "unit": "PK",
    "price": "0.00",
    "note": "WFM 무상 입고",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spacer",
    "purpose": "생산",
    "name": "1.5T",
    "spec": "",
    "lotNo": "CID01",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "1750.00",
    "note": "인동첨단소재 구매, 16pi",
    "stock": 100
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spacer",
    "purpose": "생산",
    "name": "1.0T",
    "spec": "",
    "lotNo": "CID02",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "756.00",
    "note": "인동첨단소재 구매, (5종 set 단가 3,780원)",
    "stock": 264
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Gasket",
    "purpose": "생산",
    "name": "PP Gasket",
    "spec": "",
    "lotNo": "CID03",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "756.00",
    "note": "인동첨단소재 구매, (5종 set 단가 3,780원)",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Case",
    "purpose": "생산",
    "name": "Case",
    "spec": "",
    "lotNo": "CID04",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "756.00",
    "note": "인동첨단소재 구매, (5종 set 단가 3,780원)",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Cap",
    "purpose": "생산",
    "name": "Cap",
    "spec": "",
    "lotNo": "CID05",
    "company": "웰코스",
    "origin": "국내",
    "unit": "ea",
    "price": "756.00",
    "note": "인동첨단소재 구매, (5종 set 단가 3,780원)",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Spring",
    "purpose": "생산",
    "name": "Wave Spring",
    "spec": "",
    "lotNo": "CID06",
    "company": "웰코스",
    "origin": "국내",
    "unit": "PK",
    "price": "756.00",
    "note": "인동첨단소재 구매, (5종 set 단가 3,780원)",
    "stock": 200
  },
  {
    "process": "조립",
    "category": "코인셀부품",
    "type": "Li metal",
    "purpose": "개발",
    "name": "Lithium metal",
    "spec": "0.5T, W39mm, 125g=1pk",
    "lotNo": "CID07",
    "company": "HONJO METAL",
    "origin": "해외",
    "unit": "PK",
    "price": "0.00",
    "note": "인동첨단소재 구매",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "테이프",
    "type": "PP(Green)",
    "purpose": "생산",
    "name": "ST-PP2532DG(HF)",
    "spec": "W65*0.5M",
    "lotNo": "A22724F06009",
    "company": "대현에스티",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 27
  },
  {
    "process": "조립",
    "category": "테이프",
    "type": "PP(Green)",
    "purpose": "생산",
    "name": "ST-5595DG(HF)",
    "spec": "W10*1.5M",
    "lotNo": "22621F9-02",
    "company": "대현에스티",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 21
  },
  {
    "process": "조립",
    "category": "테이프",
    "type": "PI(Yellow)",
    "purpose": "생산",
    "name": "ST-5399WA",
    "spec": "W10*0.7M 1roll, 1.4M 16roll, 0.03T",
    "lotNo": "22702F9-14",
    "company": "대현에스티",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 16
  },
  {
    "process": "조립",
    "category": "테이프",
    "type": "PI(Yellow)",
    "purpose": "생산",
    "name": "3331 AW",
    "spec": "W10*8M",
    "lotNo": "sample2",
    "company": "테이팩스",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 1
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Can",
    "purpose": "불용",
    "name": "Al Can",
    "spec": "",
    "lotNo": "UA01",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 541
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Cap",
    "purpose": "불용",
    "name": "Al Cap",
    "spec": "",
    "lotNo": "UA02",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "26ea 테스트용 추가 보유중",
    "stock": 267
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Cap",
    "purpose": "불용",
    "name": "Cu Cap",
    "spec": "",
    "lotNo": "UA03",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "22ea 테스트용 추가 보유중",
    "stock": 70
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "CC",
    "purpose": "불용",
    "name": "Al CC",
    "spec": "",
    "lotNo": "UA04",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 1056
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "CC",
    "purpose": "불용",
    "name": "Cu CC",
    "spec": "",
    "lotNo": "UA05",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 161
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "핀",
    "purpose": "불용",
    "name": "주액구 핀",
    "spec": "",
    "lotNo": "UA06",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 1653
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Insulation sheet",
    "purpose": "불용",
    "name": "절연 sheet",
    "spec": "",
    "lotNo": "UA07",
    "company": "JV코리아",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 720
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "가실핀",
    "purpose": "불용",
    "name": "가실핀",
    "spec": "",
    "lotNo": "UA08",
    "company": "SNF",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 3055
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Cap",
    "purpose": "불용",
    "name": "Al Cap(구형)",
    "spec": "",
    "lotNo": "UA09",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "각형(구형)",
    "stock": 389
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Cap",
    "purpose": "불용",
    "name": "Cu Cap(구형)",
    "spec": "",
    "lotNo": "UA10",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "각형(구형)",
    "stock": 306
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "CC",
    "purpose": "불용",
    "name": "Al CC(구형)",
    "spec": "",
    "lotNo": "UA11",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "각형(구형)",
    "stock": 1314
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "CC",
    "purpose": "불용",
    "name": "Cu CC(구형)",
    "spec": "",
    "lotNo": "UA12",
    "company": "태화기업",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "각형(구형)",
    "stock": 345
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Insulation sheet",
    "purpose": "불용",
    "name": "insulation sheet (160um, 169x270)",
    "spec": "PP 160um (169mm*270mm)",
    "lotNo": "UA13",
    "company": "jv코리아",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 290
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "Insulation sheet",
    "purpose": "불용",
    "name": "insulation sheet (160um)",
    "spec": "PP 160um",
    "lotNo": "UA14",
    "company": "jv코리아",
    "origin": "국내",
    "unit": "ea",
    "price": "0.00",
    "note": "",
    "stock": 873
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "단면",
    "purpose": "불용",
    "name": "MC-PC S12E9W3S",
    "spec": "12um x 125mm",
    "lotNo": "S12C1S3200908A01",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 3000
  },
  {
    "process": "조립",
    "category": "각형",
    "type": "단면",
    "purpose": "불용",
    "name": "MS-PCS 19E16S3S",
    "spec": "19um x 125mm",
    "lotNo": "S19C1S3201222A02",
    "company": "Enerever",
    "origin": "국내",
    "unit": "m",
    "price": "0.00",
    "note": "",
    "stock": 2000
  }
] as const;
