export enum LqcProcessType {
  MIXING_CATHODE = 'MIXING_CATHODE',
  MIXING_ANODE = 'MIXING_ANODE',
  COATING_CATHODE = 'COATING_CATHODE',
  COATING_ANODE = 'COATING_ANODE',
  PRESS_CATHODE = 'PRESS_CATHODE',
  PRESS_ANODE = 'PRESS_ANODE',
  VD_CATHODE = 'VD_CATHODE',
  VD_ANODE = 'VD_ANODE',
}

export enum LqcItemType {
  BINDER = 'BINDER',
  SLURRY = 'SLURRY',
  COATING = 'COATING',
  PRESS = 'PRESS',
  VD = 'VD',
}
